### ISSUE TITLE
SyliusStore plugin review

### ISSUE THREAD

**Issue by Zales0123** [Berezhnov/sylius-smartarget-whatsapp-contact-us#1]
Hello!

I'm Mateusz, Sylius Core Team Member, I'm also responsible for reviewing submitted Sylius plugins. Thank you for the submission though :) I have a few questions/doubts regarding the plugin.

- why the plugin does not support PHP 7.3 and 7.4?
- Plugins supports Sylius ~1.3 which is not maintained since 1.02.2020... I can understand why you want to support more Sylius versions, but as far as we know, there are almost none applications using Sylius below 1.5 now :)
- "--no-scripts" required during "composer require" - without that, it results in an exception ` You have requested a non-existent parameter "smartarget_smartarget_whatsapp_contact_us.model.message.class".`
- It seems it's not possible to manage "Logged-in customers only" configuration (no checkbox in the form)

After fixing/answering to these questions, I would be glad to accept this plugin and add it to our Store 🖖

**Comment by Berezhnov** [comment]
Hi!

1) Plugin supports PHP 7.3/7.4. There is no difference.
2) Is there any breaking changes since 1.3? May be just change version in config and that’s it?
3) Yes, I know there is an exception. Because my recipes not working, I can’t publish them into symfony git. So just after composer require user have to place files as I described in README.
4) I removed that option. Is it necessary?

**Comment by Zales0123** [comment]
1) According to the [information in composer.json](https://github.com/Berezhnov/sylius-smartarget-whatsapp-contact-us/blob/main/composer.json#L14) it does not :/ Also, when I tried to install it on my PHP 7.4.11 I got such information:
<img width="1157" alt="Zrzut ekranu 2021-01-12 o 13 32 42" src="https://user-images.githubusercontent.com/6212718/104315049-a7d09300-54da-11eb-8b95-9341fdaf7575.png">

2) There were no BC breaks, but still, it would be reasonable to go through the UPGRADE files in Sylius (https://github.com/Sylius/Sylius/blob/master/UPGRADE-1.3.md) and see if anything needs to be changed in the plugin itself

3) Using `composer require smartarget/sylius-smartarget-whatsapp-contact-us-plugin --no-scripts` would avoid that exception, so it should be mentioned in the documentation until this problem would not occur :)

4) I would say that if such an option is available (from the entity point of view), really works and is displayed in the grid, **but** not manageable in the form... then it leads to a little confusion for the application user 💃

**Comment by Berezhnov** [comment]
@Zales0123 Hi! package updated

1. Changed version. Now it is 7.2 >
2. Sylius version changed to 1.5+
3. Readme changed
4. Option removed from app.

**Comment by Zales0123** [comment]
Hi, thank you for changes :) Its looks good now. The only thing I would add is the point with adding `Smartarget\SyliusSmartargetWhatsappContactUsPlugin\SmartargetSyliusSmartargetWhatsappContactUsPlugin::class => ['all' => true],` to the `bundles.php`, as it's not added automatically anymore (due to `--no-scripts` option).

Rest is good, I will add the plugin to the store in the nearest days 🖖 🎉

**Comment by Berezhnov** [comment]
@Zales0123 README.md fixed. 

Thanks!

**Comment by mounmouc** [comment]
The issue is still ongoing with the version?
![version-wgatsup](https://github.com/Berezhnov/sylius-smartarget-whatsapp-contact-us/assets/8937677/4d8c8668-9be1-45a2-893b-9a7058c29f16)

**Comment by erezson** [comment]
Hey, 
The most easy and quick solution would be to add the Smartarget integration code (it's one line of JS) to your theme before the </body>. You can find it in your Smartarget Dashboard: https://app.smartarget.online/#/integration
